version: '3.8'

services:
  server:
    build: ./server
    container_name: todo-server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_ATLAS_URI=${MONGODB_ATLAS_URI}  # Injected by Jenkins
      - JWT_SECRET=${JWT_SECRET}                # Injected by Jenkins
    restart: unless-stopped

  client:
    build: ./client
    container_name: todo-client
    ports:
      - "3000:80"
    restart: unless-stopped